### PR TITLE
Support building of docker images

### PR DESCRIPTION
**Pull request by pcfens**
The various changes include support for building docker images using best practice secret protection as well as basic documentation.

After this is merged, the Docker hub organization name (wmit) should be updated to something more official (mdid or vrchost?). To keep images up to date it'd be worth considering using [automated builds](https://docs.docker.com/docker-hub/builds/#create-an-automated-build) too, but that's all for later.

### CODE REVIEW

**Comment by knabar** [comment]
@pcfens Thanks for this, I think this will be very helpful.  I'm planning on merging in a few days, after I make the final 3.2 release and clean up the branches.

**Comment by pcfens** [comment]
Sounds like a good plan to me. Let me know if you'd like for me to change the target branch.

I may need to make a small change to the Dockerfile for solr with the recent release of Docker 17.06 (it seems to be handling remote tar files differently on add).

Hopefully we can get automated builds set up on the Docker hub too.

**Comment by pcfens** [comment]
Thanks for merging - do you want to set up an automated build on the Docker Hub? You really just need an organization setup and your account linked to GitHub and they'll take care of building and hosting.

**Comment by knabar** [comment]
@pcfens I created an automated build at https://hub.docker.com/r/vrchost/rooibos/, but have not looked into it any further

**Pull request merged**
